// Edit content here. Use paths relative to this site's dist folder.
// video: null OR { type: 'mp4', src: 'assets/videos/film.mp4' }
// OR { type: 'youtube', src: 'https://www.youtube.com/watch?v=VIDEO_ID' }
// OR { type: 'vimeo', src: 'https://vimeo.com/VIDEO_ID' }
window.portfolio = {
 showreel: {type:'youtube',src:'https://youtu.be/wZxs1kt6Q0o'},
 portrait: { src: 'assets/images/isaac-portrait.webp', alt: 'Isaac Callender-Barlow, Video Editor' },
 projects: [
 {id:'dj-ag',recognition:['Instagram Rings · Supporting editor','Audience growth'],date:'2024–2025',title:'DJ AG',client:'DJ AG',role:'Video Editor',type:'Music / Performance',description:'Edited music and performance content for an audience of more than 2 million across social platforms. Multi-camera, drone and gimbal footage for Instagram, TikTok and YouTube. Contributed editing work that supported DJ AG’s Instagram Rings recognition and helped grow his following.',thumbnail:'assets/images/dj-ag-cover.webp',alt:'DJ AG Open Mic cover',channel:'https://www.youtube.com/@djagonline2.0/featured',video:{type:'youtube',src:'https://www.youtube.com/watch?v=OlLCuZ0RZMs'}},
 {id:'aff-productions',recognition:['Multi-award-winning film'],date:'2024',title:'Man with News',client:'AFF Productions',role:'Video Editor',type:'Award-winning short film',description:'Edited a multi-award-winning short film, with a focus on narrative storytelling, pacing, colour grading and immersive sound design.',thumbnail:'assets/images/aff-productions-cover.webp',alt:'Man with News film cover',video:{type:'youtube',src:'https://youtu.be/2naWXN3XRJc'}},
 {id:'complete-fertility',date:'2024',title:'Complete Fertility',client:'Complete Fertility',role:'Director / Video Editor',type:'Promotional',description:'Directed and edited promotional content for a newly privatised fertility clinic, taking professional storytelling from production through final edit.',thumbnail:'assets/images/complete-fertility-cover.webp',alt:'Video thumbnail for Complete Fertility',video:{type:'youtube',src:'https://youtu.be/8hisKf-xMRI'}},
 {id:'red-bull',date:'2024',title:'Red Bull Gaming Sphere',client:'Red Bull Gaming Sphere',role:'Videographer / Video Editor',type:'Gaming / Promotional',description:'Filmed and edited promotional content showcasing the facilities, atmosphere and events. Handled production through final edit.',thumbnail:'assets/images/red-bull-cover.webp',alt:'Video thumbnail for Red Bull Gaming Sphere',video:{type:'youtube',src:'https://youtu.be/V-M3skCl498'}},
 {id:'ab-studios',date:'2023',title:'This Is Fine',client:'AB Studios',role:'Video Editor',type:'Short film',description:'Edited a professionally produced short film, with a focus on visual storytelling, colour grading, sound design and pacing.',thumbnail:'assets/images/ab-studios-cover.webp',alt:'This Is Fine film cover',video:{type:'youtube',src:'https://youtu.be/3ZOd9uj0VXE'}},
 {id:'hillary',date:'',title:'Hillary',client:'',role:'Video Editor',type:'Short film',description:'Short film edited by Isaac Callender-Barlow.',thumbnail:'assets/images/hillary-cover.webp',alt:'Hillary short film cover',video:{type:'youtube',src:'https://youtu.be/VF88xK6Zvss'}},
 {id:'hsdc-tournament',date:'2021',title:'HSDC Sponsored Tournament',client:'HSDC',role:'Producer',type:'Esports / Event production',description:'Produced an online gaming tournament during COVID. Responsibilities included event production, coordination, sponsored content, tournament delivery and prize-related production.',thumbnail:'assets/images/hsdc-cup-cover.webp',alt:'Custom HSDC Rocket League Cup cover artwork',video:{type:'youtube',src:'https://www.youtube.com/watch?v=1FOiHSBXtOU&t=798s'}}
 ],
 // Empty logo paths show honest text placeholders. Add supplied monochrome logos here.
 clients:[{name:"L’Oréal",logo:'assets/logos/loreal.svg?v=6.1'},{name:'Unilever',logo:'assets/logos/unilever.svg'},{name:'Kenvue',logo:'assets/logos/kenvue.svg'},{name:'Nestlé',logo:'assets/logos/nestle.svg'},{name:'Colgate-Palmolive',logo:'assets/logos/colgate-palmolive.svg'},{name:'Procter & Gamble',logo:'assets/logos/pg.svg'},{name:'Henkel',logo:'assets/logos/henkel.svg'},{name:'Reckitt',logo:'assets/logos/reckitt.svg'},{name:'Champion Petfoods',logo:'assets/logos/champion.svg'}]
};
