import {el,button,avatar} from './secret-ui.js?v=5';
export function startBoss(ui){
 const wrap=el('section','boss-wrap');ui.body.append(wrap);wrap.append(el('p','secret-kicker','UNAUTHORISED KNOWLEDGE DETECTED'),el('h1','','8-BIT ISAAC'));const hud=el('div','boss-hud'),health=el('progress');health.setAttribute('aria-label','Isaac health');health.max=180;health.value=180;const lives=el('span','','YOU ♥ ♥ ♥ ♥ ♥');hud.append(el('span','','ISAAC'),health,lives);const canvas=el('canvas','boss-canvas');canvas.width=720;canvas.height=480;canvas.tabIndex=0;canvas.setAttribute('aria-label','Isaac boss battle. Arrow keys or WASD to move, hold Space to fire.');const status=el('p','secret-live','Move with WASD / arrows. Hold Space to fire. Dodge the pink pixels.');status.setAttribute('role','status');const controls=el('div','secret-actions');const start=button('Start fight',reset,'primary'),pause=button('Pause',()=>{if(!playing)return;paused=!paused;pause.textContent=paused?'Resume':'Pause';if(!paused)canvas.focus();});controls.append(start,pause);wrap.append(hud,canvas,status,controls);const touch=el('div','boss-touch'),directions=el('div');const keys=new Set();for(const [text,key]of [['←','ArrowLeft'],['↑','ArrowUp'],['↓','ArrowDown'],['→','ArrowRight']])directions.append(holdButton(text,key));touch.append(directions,holdButton('FIRE',' '));wrap.append(touch,el('p','secret-muted','A short arcade encounter. No sound. Escape returns to the portfolio.'));
 const ctx=canvas.getContext('2d'),img=new Image();img.src=avatar;let x=360,y=405,bx=360,hp=180,life=5,bullets=[],shots=[],t=0,last=0,frame=0,playing=false,paused=false,shotTime=0,attackTime=0,invulnerable=0,flash=0,closed=false;
 function holdButton(text,key){const b=button(text,()=>{});b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key);});['pointerup','pointercancel','lostpointercapture'].forEach(event=>b.addEventListener(event,()=>keys.delete(key)));return b;}
 function reset(){x=360;y=405;hp=180;life=5;bullets=[];shots=[];t=0;shotTime=attackTime=invulnerable=flash=0;playing=true;paused=false;keys.clear();pause.textContent='Pause';start.textContent='Restart';status.textContent='Keep moving. Isaac is protecting the final cut.';health.value=hp;canvas.focus();}
 function end(won){playing=false;keys.clear();status.textContent=won?'ISAAC DEFEATED — YOU KNOW TOO MUCH.':'RENDER FAILED. Isaac wins this round.';start.textContent=won?'Rematch':'Try again';start.focus();}
 function down(e){if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','w','a','s','d'].includes(e.key)&&!e.target.closest('button')){e.preventDefault();keys.add(e.key);}}const up=e=>keys.delete(e.key);window.addEventListener('keydown',down);window.addEventListener('keyup',up);const blur=()=>{keys.clear();if(playing){paused=true;pause.textContent='Resume';}};window.addEventListener('blur',blur);const visibility=()=>{if(document.hidden)blur();};document.addEventListener('visibilitychange',visibility);
 function update(dt){t+=dt;invulnerable=Math.max(0,invulnerable-dt);flash=Math.max(0,flash-dt);const dx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),dy=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0),speed=260*dt/(dx&&dy?Math.SQRT2:1);x=Math.max(14,Math.min(706,x+dx*speed));y=Math.max(175,Math.min(462,y+dy*speed));bx=360+Math.sin(t*.85)*225;shotTime-=dt;attackTime-=dt;if(keys.has(' ')&&shotTime<=0){shots.push({x,y:y-14});shotTime=.23;}if(attackTime<=0){const rage=hp<90;const a=Math.atan2(y-110,x-bx);for(let i=-1;i<=1;i++)bullets.push({x:bx,y:115,vx:Math.cos(a+i*.25)*(rage?150:115),vy:Math.sin(a+i*.25)*(rage?150:115)});if(rage)for(let i=0;i<7;i++)bullets.push({x:bx,y:110,vx:Math.cos(i*Math.PI/6)*125,vy:Math.sin(i*Math.PI/6)*125});attackTime=rage?1.15:1.55;}
 shots=shots.filter(s=>{s.y-=420*dt;if(Math.abs(s.x-bx)<43&&s.y<125&&s.y>40){hp=Math.max(0,hp-2);flash=.07;return false;}return s.y>-10;});bullets=bullets.filter(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;if(Math.hypot(b.x-x,b.y-y)<11&&!invulnerable){life--;invulnerable=2.4;return false;}return b.y<500&&b.x>-20&&b.x<740;});health.value=hp;lives.textContent='YOU '+('♥ '.repeat(Math.max(0,life)))+('♡ '.repeat(5-Math.max(0,life)));if(hp<=0)end(true);else if(life<=0)end(false);}
 function draw(){ctx.fillStyle='#070e1b';ctx.fillRect(0,0,720,480);ctx.strokeStyle='#17263e';ctx.lineWidth=1;for(let i=0;i<720;i+=40){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,480);ctx.stroke();}for(let i=0;i<480;i+=40){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(720,i);ctx.stroke();}ctx.imageSmoothingEnabled=false;if(img.complete&&img.naturalWidth)ctx.drawImage(img,bx-42,32,84,84);else{ctx.fillStyle='#9ba7e7';ctx.fillRect(bx-32,40,64,64);}if(flash){ctx.fillStyle='#ffffff70';ctx.fillRect(bx-42,32,84,84);}ctx.fillStyle=hp<90?'#f177aa':'#b5a4fa';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText(hp<90?'ISAAC // FINAL FORM':'ISAAC // 198X',bx,23);ctx.fillStyle=invulnerable?'#ffd093':'#96d9f1';ctx.fillRect(x-12,y-8,24,16);ctx.fillRect(x-4,y-15,8,8);ctx.fillStyle='#afe9ff';shots.forEach(s=>ctx.fillRect(s.x-2,s.y,4,12));ctx.fillStyle='#ef78a8';bullets.forEach(b=>ctx.fillRect(b.x-4,b.y-4,8,8));if(!playing||paused){ctx.fillStyle='#070e1bc9';ctx.fillRect(0,160,720,150);ctx.fillStyle='#e1eaf9';ctx.font='22px monospace';ctx.fillText(paused?'PAUSED':hp<=0?'ISAAC DEFEATED':life<=0?'RENDER FAILED':'YOU KNOW TOO MUCH.',360,224);ctx.font='13px monospace';ctx.fillText(paused?'Resume when ready.':hp<=0?'YOU KNOW TOO MUCH.':'Move. Dodge. Hold FIRE.',360,255);}}
 function tick(now){if(closed)return;const dt=Math.min((now-last)/1000,.035);last=now;if(playing&&!paused)update(dt);draw();frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);ui.cleanup.push(()=>{closed=true;cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);keys.clear();});
}
