import {Chess} from './vendor/chess.js';
import {shell,el,button,avatar} from './secret-ui.js?v=5';
export async function open(onClose){
 const ui=shell('Chess against Isaac',onClose),game=new Chess();let worker,selected=null,pending=null,ended=false,thinking=false,job=0,drag=null,skipClick=false,lastMove=null,clock=[600,600],last=performance.now(),started=false,closed=false;
 ui.cleanup.push(()=>{closed=true;});
 const intro=el('div','pixel-intro');const face=el('img');face.src=avatar;face.alt='Pixel-art Isaac';intro.append(face,el('h1','','ISAAC / 1000'),el('p','secret-muted','A different kind of editing. Your move.'));ui.body.append(intro);
 await new Promise(resolve=>setTimeout(resolve,matchMedia('(prefers-reduced-motion:reduce)').matches?80:600));if(closed)return;
 ui.body.replaceChildren();const layout=el('div','chess-layout'),left=el('section'),right=el('aside','secret-card');const opponent=el('div','player-row'),av=el('img','pixel-avatar');av.src=avatar;av.alt='Isaac Bot';const label=el('div');label.append(el('strong','','ISAAC'),el('span','secret-muted','1000 · casual bot'));const blackClock=el('span','clock','10:00');opponent.append(av,label,blackClock);
 const board=el('div','chess-board');board.setAttribute('role','group');board.setAttribute('aria-label','Chess board. You play White.');const player=el('div','player-row'),whiteClock=el('span','clock','10:00');player.append(el('strong','','YOU / WHITE'),whiteClock);left.append(opponent,board,player);
 const status=el('p','secret-live','Your move.');status.setAttribute('role','status');const promotion=el('div','promotion');const captures=el('p','secret-muted');const history=el('div','chess-history');history.setAttribute('aria-label','Move history');const actions=el('div','secret-actions');actions.append(button('Resign',()=>{if(!ended){ended=true;job++;status.textContent='You resigned. Isaac wins.';render();}}),button('Restart / Rematch',reset));right.append(el('p','secret-kicker','AFTER HOURS / CHESS'),el('h2','','Your move, editor.'),el('p','secret-muted','10-minute clocks · Click or drag a piece. Clocks pause when this tab is hidden. Bot strength is approximate, not a rated engine.'),status,promotion,captures,history,actions);layout.append(left,right);ui.body.append(layout);
 const symbols={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
 const names={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'};
 function makeWorker(){worker=new Worker(new URL('./chess-ai.js?v=5',import.meta.url),{type:'module'});worker.onmessage=e=>{if(closed||ended||e.data.id!==job)return;const move=e.data.move||game.moves()[0];if(move){lastMove=game.move(move);thinking=false;last=performance.now();finish();render();}};worker.onerror=()=>{if(!closed&&!ended&&game.turn()==='b'){lastMove=game.move(game.moves()[0]);thinking=false;finish();render();}};}makeWorker();
 function finish(){if(game.isCheckmate()){ended=true;status.textContent=game.turn()==='w'?'Checkmate. Isaac wins.':'Checkmate. You beat Isaac!';}else if(game.isDraw()){ended=true;status.textContent=game.isStalemate()?'Draw by stalemate.':game.isThreefoldRepetition()?'Draw by repetition.':game.isInsufficientMaterial()?'Draw: insufficient material.':'Draw by the fifty-move rule.';}else status.textContent=(game.turn()==='w'?'Your move.':'Isaac is thinking…')+(game.isCheck()?' Check!':'');}
 function render(){if(ended){pending=null;promotion.replaceChildren();}board.replaceChildren();const legal=selected&&!ended?game.moves({square:selected,verbose:true}):[];for(let r=8;r>=1;r--)for(let f=0;f<8;f++){const square=String.fromCharCode(97+f)+r,piece=game.get(square);const b=button(piece?symbols[piece.color+piece.type]:'',()=>{if(skipClick)return;pick(square);},'square'+((r+f)%2?' dark':'')+(piece?.color==='w'?' white-piece':''));b.dataset.square=square;b.setAttribute('aria-label',square+(piece?' '+(piece.color==='w'?'White ':'Black ')+names[piece.type]:' empty'));if(square===selected)b.classList.add('selected');if(lastMove&&(lastMove.from===square||lastMove.to===square))b.classList.add('last');if(legal.some(m=>m.to===square))b.classList.add('legal',piece?'capture':'legal');if(piece?.type==='k'&&piece.color===game.turn()&&game.isCheck())b.classList.add('check');if(r===1||f===0)b.append(el('small','',(f===0?r:'')+(r===1?String.fromCharCode(97+f):'')));board.append(b);}
 const moves=game.history();history.textContent=moves.reduce((s,m,i)=>s+(i%2?' '+m+'\n':(i/2+1)+'. '+m),'');history.scrollTop=history.scrollHeight;captures.textContent='Captured: '+(game.history({verbose:true}).filter(m=>m.captured).map(m=>symbols[(m.color==='w'?'b':'w')+m.captured]).join(' ')||'—');}
 function pick(square){if(ended||thinking||pending||game.turn()!=='w')return;const piece=game.get(square);if(selected){const move=game.moves({square:selected,verbose:true}).find(m=>m.to===square);if(move){if(move.promotion){pending={from:selected,to:square};promotion.replaceChildren(el('span','','Promote:'));['q','r','b','n'].forEach(p=>promotion.append(button(symbols['w'+p],()=>{const next={...pending,promotion:p};pending=null;promotion.replaceChildren();play(next);})));return;}play({from:selected,to:square});return;}}selected=piece?.color==='w'?square:null;render();}
 function play(move){if(ended||thinking)return;try{lastMove=game.move(move);}catch{return;}selected=null;started=true;last=performance.now();finish();render();if(!ended){thinking=true;const id=++job;setTimeout(()=>{if(!closed&&!ended&&job===id)worker.postMessage({id,fen:game.fen()});},350+Math.random()*300);}}
 board.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-square]');if(!b||game.get(b.dataset.square)?.color!=='w'||thinking||ended)return;drag={square:b.dataset.square,x:e.clientX,y:e.clientY};});
 const release=e=>{if(!drag)return;const origin=drag;drag=null;const moved=Math.hypot(e.clientX-origin.x,e.clientY-origin.y)>8;if(!moved)return;skipClick=true;setTimeout(()=>skipClick=false,0);const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-square]');selected=origin.square;if(target)pick(target.dataset.square);else render();};window.addEventListener('pointerup',release);const cancelDrag=()=>{drag=null;};window.addEventListener('pointercancel',cancelDrag);
 function reset(){job++;worker.terminate();makeWorker();game.reset();selected=pending=lastMove=null;ended=thinking=started=false;clock=[600,600];last=performance.now();promotion.replaceChildren();status.textContent='Your move.';render();updateClock();}
 function updateClock(){const now=performance.now();if(started&&!ended&&!document.hidden){const i=game.turn()==='w'?0:1;clock[i]=Math.max(0,clock[i]-(now-last)/1000);if(!clock[i]){ended=true;job++;const opponent=i===0?'b':'w';const canMate=game.board().flat().some(p=>p&&p.color===opponent&&p.type!=='k');status.textContent=canMate?(i===0?'Your':'Isaac’s')+' time ran out. '+(i===0?'Isaac':'You')+' wins.':'Draw on time: the opponent has only a king.';}}last=now;const fmt=t=>Math.floor(Math.ceil(t)/60).toString().padStart(2,'0')+':'+(Math.ceil(t)%60).toString().padStart(2,'0');whiteClock.textContent=fmt(clock[0]);blackClock.textContent=fmt(clock[1]);}
 const interval=setInterval(updateClock,100);const visibility=()=>{last=performance.now();};document.addEventListener('visibilitychange',visibility);ui.cleanup.push(()=>{closed=true;job++;worker.terminate();clearInterval(interval);window.removeEventListener('pointerup',release);window.removeEventListener('pointercancel',cancelDrag);document.removeEventListener('visibilitychange',visibility);});render();
}
