import {shell,el,button} from './secret-ui.js?v=5';
import {createRun,stepRun,hazards,WIDTH,FLOOR,DURATION} from './runner-engine.js?v=1';

export function open(onClose){
 const ui=shell('ICB Media Encoder — secret export',onClose);ui.d.classList.add('runner-shell');
 const window=el('section','encoder-window');ui.body.append(window);const top=el('div','encoder-top');top.append(el('span','encoder-icon','ICB'),el('span','','MEDIA ENCODER'),el('span','encoder-version','AFTER HOURS / BUILD 1986'));window.append(top);
 const tabs=el('div','encoder-tabs');tabs.append(el('span','selected','Queue'),el('span','','Encoding log'),el('span','','System status'));window.append(tabs);
 const file=el('div','encoder-file');file.append(el('span','encoder-file-icon','▤'),el('div'));file.lastChild.append(el('strong','','secret_after_hours_FINAL_v09.mp4'),el('p','secret-muted','H.264 · 1920 × 1080 · Match source / High bitrate'));const badge=el('span','encoder-state','QUEUED');file.append(badge);window.append(file);
 const content=el('div','encoder-content');window.append(content);let state=null,frame=0,last=0,closed=false,paused=false,jump=false,duck=false,keys=new Set(),canvas,ctx,progress,status,hud,pause,clock;
 const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 const handlerController=new AbortController();
 function intro(){content.replaceChildren();const headline=el('div','encoder-intro');headline.append(el('p','secret-kicker','ESTIMATED TIME REMAINING'),el('div','encoder-eta','99:59:59'),el('h1','','We’ll be here all night.'),el('p','secret-muted','One floppy disk. A timeline full of problems. Your export is waiting for a little hands-on acceleration.'));const action=button('Enable accelerated rendering →',start,'primary');headline.append(action,el('p','runner-instructions','↑ / Space to jump · ↓ to duck · Three recovery attempts'));content.append(headline);}
 function start(){cancelAnimationFrame(frame);state=createRun();paused=false;jump=duck=false;keys.clear();badge.textContent='ENCODING';badge.className='encoder-state encoding';content.replaceChildren();const bar=el('div','runner-progress');progress=el('progress');progress.max=100;progress.value=0;progress.setAttribute('aria-label','Export progress');hud=el('span','','0%');bar.append(progress,hud);canvas=el('canvas','runner-canvas');canvas.width=matchMedia('(max-width:650px)').matches?640:WIDTH;canvas.height=350;canvas.tabIndex=0;canvas.setAttribute('aria-label','Floppy disk runner. Space or Up jumps. Hold Down to duck audio sync warnings.');ctx=canvas.getContext('2d');clock=el('div','runner-meta');status=el('p','secret-live','Jump the render errors. Duck the audio warnings. Keep this export alive.');status.setAttribute('role','status');const actions=el('div','secret-actions');pause=button('Pause',()=>{if(state.status!=='running')return;paused=!paused;pause.textContent=paused?'Resume':'Pause';if(!paused){canvas.focus({preventScroll:true});last=performance.now();}});actions.append(pause,button('Restart export',start));const touch=el('div','runner-touch');const jb=button('↑ JUMP',()=>{jump=true;});const db=button('↓ HOLD TO DUCK',()=>{});db.addEventListener('pointerdown',e=>{e.preventDefault();db.setPointerCapture(e.pointerId);duck=true;});['pointerup','pointercancel','lostpointercapture'].forEach(type=>db.addEventListener(type,()=>duck=false));db.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();duck=true;}});db.addEventListener('keyup',()=>duck=false);db.addEventListener('blur',()=>duck=false);touch.append(jb,db);content.append(bar,canvas,clock,status,touch,actions,el('p','runner-instructions','↑ / Space: jump · hold ↓: duck · P: pause · Escape: return'));ui.d.scrollTop=0;canvas.focus({preventScroll:true});last=performance.now();frame=requestAnimationFrame(tick);}
 function finish(){cancelAnimationFrame(frame);const won=state.status==='complete';badge.textContent=won?'DONE':'FAILED';badge.className='encoder-state '+(won?'complete':'failed');content.replaceChildren();const result=el('div','encoder-result');result.append(el('div','export-result-icon',won?'✓':'!'),el('p','secret-kicker',won?'STATUS / SUCCESS':'STATUS / ENCODING FAILED'),el('h1','',won?'Export complete.':'Render failed.'),el('p','',won?'secret_after_hours_FINAL_v09.mp4':"The timeline fought back. Your export didn’t make it."));const details=el('dl','export-details');for(const [term,value]of won?[['Progress','100%'],['Elapsed time',Math.round(state.time)+' seconds'],['Output','Secret unlocked. Sanity mostly intact.']]:[['Progress',Math.floor(state.time/DURATION*100)+'%'],['Error','Three unrecoverable timeline faults'],['Recovery','Re-queue and try again']])details.append(el('dt','',term),el('dd','',value));result.append(details);const actions=el('div','secret-actions');actions.append(button(won?'Return to Portfolio ↗':'Retry accelerated export',won?ui.close:start,'primary'),button(won?'Re-queue export':'Return to Portfolio ↗',won?start:ui.close));result.append(actions);content.append(result);result.setAttribute('role','status');actions.querySelector('button').focus();}
 function draw(){
  ctx.fillStyle='#0c1423';ctx.fillRect(0,0,WIDTH,350);ctx.imageSmoothingEnabled=false;
  ctx.strokeStyle='#1c2b42';ctx.lineWidth=1;for(let x=-(reduced?0:state.distance*.15)%48;x<WIDTH;x+=48){ctx.beginPath();ctx.moveTo(x,35);ctx.lineTo(x,FLOOR);ctx.stroke();}for(let y=52;y<FLOOR;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WIDTH,y);ctx.stroke();}
  ctx.fillStyle='#172940';ctx.fillRect(0,FLOOR,WIDTH,58);ctx.fillStyle='#91cbd8';ctx.fillRect(0,FLOOR,WIDTH,2);ctx.fillStyle='#28425c';for(let x=-(reduced?0:state.distance)%70;x<WIDTH;x+=70)ctx.fillRect(x,FLOOR+23,36,3);
  ctx.font='12px monospace';ctx.textAlign='left';ctx.fillStyle='#7791ad';ctx.fillText('SEQUENCE: EDITOR’S WORST NIGHTMARE',20,25);ctx.textAlign='right';ctx.fillText('RENDER SPEED '+(state.speed/250).toFixed(2)+'×',canvas.width-20,25);
  for(const o of state.obstacles){const h=hazards[o.type],y=FLOOR-h.height-h.offset;ctx.globalAlpha=o.hit?.35:1;ctx.fillStyle=h.color;ctx.fillRect(o.x,y,h.width,h.height);ctx.fillStyle='#171e30';ctx.fillRect(o.x+3,y+3,h.width-6,h.height-6);ctx.fillStyle=h.color;ctx.font='bold 11px monospace';ctx.textAlign='center';const words=h.label.split(' ');if(o.type==='sync'){ctx.fillText('AUDIO OUT',o.x+h.width/2,y+15);ctx.fillText('OF SYNC',o.x+h.width/2,y+29);}else{ctx.fillText(words[0],o.x+h.width/2,y+21);ctx.fillText(words.slice(1).join(' '),o.x+h.width/2,y+36);}ctx.font='10px monospace';ctx.fillText(h.hint==='DUCK'?'↓ DUCK':'↑ JUMP',o.x+h.width/2,y-10);ctx.globalAlpha=1;}
  const height=state.duck?24:54,py=FLOOR-state.y-height;ctx.fillStyle=state.invulnerable>0?'#f7d59a':'#9bbbe1';ctx.fillRect(130,py,44,height);ctx.fillStyle='#1f344f';ctx.fillRect(134,py+3,27,Math.max(5,height*.35));ctx.fillStyle='#d5e5f4';ctx.fillRect(150,py+4,7,Math.max(3,height*.27));ctx.fillStyle='#e5edf5';ctx.fillRect(135,py+height*.52,34,height*.4);ctx.fillStyle='#496a8d';ctx.fillRect(140,py+height*.62,21,2);ctx.fillRect(140,py+height*.73,15,2);
  if(state.flash&&!reduced){ctx.fillStyle='#e36a8c18';ctx.fillRect(0,0,WIDTH,350);}if(paused){ctx.fillStyle='#0c1423db';ctx.fillRect(0,0,WIDTH,350);ctx.fillStyle='#dce8f5';ctx.textAlign='center';ctx.font='24px monospace';ctx.fillText('ENCODING PAUSED',canvas.width/2,170);}
 }
 function tick(now){if(closed)return;const dt=(now-last)/1000;last=now;const oldLives=state.lives;if(!paused){stepRun(state,dt,{jump,duck:duck||keys.has('ArrowDown')||keys.has('s')});jump=false;}if(state.lives<oldLives)status.textContent='Render fault recovered. '+state.lives+' recovery attempt'+(state.lives===1?'':'s')+' remaining.';const percent=Math.floor(state.time/DURATION*100);if(progress.value!==percent){progress.value=percent;hud.textContent=percent+'%';}const info='RECOVERY '+('● '.repeat(state.lives))+('○ '.repeat(3-state.lives))+' / '+(state.speed/250).toFixed(2)+'× ACCELERATION';if(clock.textContent!==info)clock.textContent=info;draw();if(state.status!=='running'){finish();return;}frame=requestAnimationFrame(tick);}
 function keydown(e){if(!state||state.status!=='running'||e.target.closest('button,input,textarea'))return;if([' ','ArrowUp','w'].includes(e.key)){e.preventDefault();if(!e.repeat)jump=true;}if(['ArrowDown','s'].includes(e.key)){e.preventDefault();keys.add(e.key);}if(e.key.toLowerCase()==='p'){e.preventDefault();pause.click();}}
 const keyup=e=>keys.delete(e.key);const blur=()=>{keys.clear();duck=jump=false;if(state?.status==='running'){paused=true;pause.textContent='Resume';}};
 globalThis.addEventListener('keydown',keydown,{signal:handlerController.signal});globalThis.addEventListener('keyup',keyup,{signal:handlerController.signal});globalThis.addEventListener('blur',blur,{signal:handlerController.signal});document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();},{signal:handlerController.signal});
 ui.cleanup.push(()=>{closed=true;cancelAnimationFrame(frame);handlerController.abort();});intro();
}
